name: Nightly Django Test

on:
  schedule:
    - cron: '0 1 * * *'
    # At 01:00, daily
  workflow_dispatch:

jobs:
  nightly-django-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: git clone https://github.com/django/django.git

      - run: python -m pip install flit
      - run: flit install --deps production --extras testing
      - run: python -m pip install ./django

      - run: python testmanage.py test
